version: '2'

services:
    proxy:
        image: nginx:latest
        links:
            - ui4docker
        ports:
            - "80:80"
        restart: always
        container_name : nginx_proxy 
        volumes:
            - ./code:/var/www/html
            - ./conf:/etc/nginx/

    ui4docker:
        image: uifd/ui-for-docker 
        container_name : ui4docker
        restart: always
#        ports:
#            - "8080:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        privileged: true

